use_frameworks!

platform :ios, '13.0'

target 'OtplessSDK_Example' do
  pod 'OtplessSDK/Core', :path => '../'
  pod 'OtplessSDK/FacebookSupport', :path => '../'
  pod 'OtplessSDK/GoogleSupport', :path => '../'

  target 'OtplessSDK_Tests' do
    inherit! :search_paths

    
  end
end
